[project]
name = "analysis_thesis"
version = "0.1.0"
requires-python = ">=3.12"
description = "A Python project for analyzing thesis data using OpenAI's API."
dependencies = [
    "openai",
    "python-dotenv",
    "clipboard",
]
